language: android
sudo: required
jdk:
  - oraclejdk8
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # in minutes (2 minutes by default)

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-26
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-26

before_script:
  - cd shot-consumer
  - mksdcard -l e 512M sdcard.img
  - echo no | android create avd --force --name test --target 'android-26' --abi armeabi-v7a --tag google_apis --device 'Nexus 4' --sdcard sdcard.img
  - emulator -avd test -skin 768x1280 -no-window &
  - cd ..

script:
  - ./gradlew checkScalafmtAll build test
  - ./gradlew install
  - cd shot-consumer
  - android-wait-for-emulator
  - sleep 300
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - ./gradlew executeScreenshotTests
