language: android
sudo: required
jdk:
  - oraclejdk8
env:
  global:
    - ADB_INSTALL_TIMEOUT=8 # in minutes (2 minutes by default)
    - ANDROID_API=26
    - EMULATOR_API=24

android:
  components:
    - tools
    - build-tools-26.0.2
    - platform-tools
    - android-$ANDROID_API
    - android-$EMULATOR_API
    - extra-android-support
    - extra-google-m2repository
    - extra-android-m2repository
    - sys-img-armeabi-v7a-google_apis-$EMULATOR_API
    - sys-img-armeabi-v7a-android-$EMULATOR_API
  licenses:
    - ".+"

before_script:
  - echo "y" | android update sdk -a --no-ui --filter android-24
  - echo "y" | android update sdk -a --no-ui --filter sys-img-armeabi-v7a-android-$EMULATOR_API
  - android list targets | grep -E '^id:' | awk -F '"' '{$1=""; print $2}'
  - android list targets
  - cd shot-consumer
  - mksdcard -l e 512M sdcard.img
  - echo no | android create avd --force --name test --target 'android-$EMULATOR_API' --abi google_apis/armeabi-v7a --sdcard sdcard.img
  - emulator -avd test -skin 768x1280 -no-window &
  - cd ..

script:
  - ./gradlew install
  - cd shot-consumer
  - android-wait-for-emulator
  - sleep 300
  - adb shell settings put global window_animation_scale 0 &
  - adb shell settings put global transition_animation_scale 0 &
  - adb shell settings put global animator_duration_scale 0 &
  - adb shell input keyevent 82 &
  - adb wait-for-device get-serialno
  - sleep 300
  - ./gradlew executeScreenshotTests
